stages:
  hori_flip:
    cmd: python code/hori_flip.py
    deps:
    - Data/Normal
    - code/hori_flip.py
  reverse:
    cmd: python code/reverse.py
    deps:
    - Data/Normal
    - code/reverse.py
  data_labelling:
    cmd: python code/data_labelling.py /home/apple/Desktop/Snehankit/Work/action_recog/code/Data_pipeline/DVC_testing/Data/sample_Sheet1.csv
     /home/apple/Desktop/Snehankit/Work/action_recog/code/Data_pipeline/DVC_testing/Data/fps_drop /home/apple/Desktop/Snehankit/Work/action_recog/code/Data_pipeline/DVC_testing/Data/Stage_1
    deps:
    - Data/sample
    - code/data_labelling.py
